version: '3'
services:
#mssql docker
  sateatar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - sateatarnet

  sateatar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=sateatar-sql,1433;Database=1589;User=sa;Password=QWElkj132!;ConnectRetryCount=250
    ports:
      - 5010:5010
    networks:
      - sateatarnet      
    links:
      - sateatar-sql
    depends_on:
      - sateatar-sql
      
networks:
  sateatarnet:
    driver: bridge