FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 5010
ENV ASPNETCORE_URLS=http://+:5010

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY . .

FROM build AS publish
RUN dotnet publish "SaTeatar" -c Release -o /app
FROM base AS final
WORKDIR /app
ADD ./SaTeatar/Images ./Images
COPY --from=publish /app .


ENTRYPOINT ["dotnet", "SaTeatar.dll"]